export const SEARCH_RESTAURANT_REQUEST = 'SEARCH_RESTAURANT_REQUEST';
export const SEARCH_RESTAURANT_SUCCESS = 'SEARCH_RESTAURANT_SUCCESS';
export const SEARCH_RESTAURANT_ERROR = 'SEARCH_RESTAURANT_ERROR';
export const RESET_SEARCH_RESTAURANT = 'RESET_SEARCH_RESTAURANT';
